name: save_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  auto_route: ^9.2.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.3
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  auto_route_generator:
  build_runner:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: DM Sans
      fonts:
        - asset: fonts/DMSans.ttf
